<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login</name>
   <tag></tag>
   <elementGuidId>0dcbe6cc-14ad-4033-9030-c34d53bf8954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'btn-block']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[normalize-space()='LOGIN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff8e9f85-8126-4e9b-b5ac-6f15d21f2c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-block</value>
      <webElementGuid>4ebf19c2-9a06-4e67-853b-6b51ccaf7e35</webElementGuid>
   </webElementProperties>
</WebElementEntity>
